name: personal_details
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  path: ^1.8.3
  path_provider: ^2.1.1
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pp.jpg
